### ISSUE TITLE
Ambiguous Exception Names

### ISSUE THREAD

**Issue by Jutanium** [GT-Jewish-DH/daf-renderer#20]
The two new CSS classes, "exception1" and "exception2", should be renamed. What do they correspond to and what triggers them?

**Comment by Shaun-Regenbaum** [comment]
I'm too tired to explain right now, ill explain tomorrow.

**Comment by Jutanium** [comment]
lmk!

**Comment by Shaun-Regenbaum** [comment]
I use them here:
![image](https://user-images.githubusercontent.com/12636260/106527055-a29cad80-64b4-11eb-9464-08c1a5232b14.png)

In short, when we are working with one of the edge cases:
![image](https://user-images.githubusercontent.com/12636260/106527306-0aeb8f00-64b5-11eb-87af-c9f44d1f65ce.png)
We have to modify the start-spacers to let one side text extend out all the way while pushing the other text all the way down into the "mid-spacer" region. In order to be able to modify the start spacers in the edge case, while not affecting the normal case, I created these two exception variables whose default values are 0, except when there is an edge case in which case the values become 1 (when inner is the smallest one then exception1 is True while exception2 is False and vice versa for outer being smallest).

**Comment by Shaun-Regenbaum** [comment]
As reference, we need to add a margin bottom to one of the start spacers in the edge case, otherwise the texts will look like they are together: 
![image](https://user-images.githubusercontent.com/12636260/106527777-cf9d9000-64b5-11eb-8ec8-edda99db83c9.png)

I was trying to think of a descriptive name for the variables, but they are literally switches. When we are in an edge case they allow one of the start spacers to have a margin bottom, otherwise it makes sure they don't have a margin bottom.

**Comment by Shaun-Regenbaum** [comment]
For further reference, we turn those values on and off in style-manager:
![image](https://user-images.githubusercontent.com/12636260/106528415-bb0dc780-64b6-11eb-959d-d25a87dbff5b.png)
And their default values in the css:
![image](https://user-images.githubusercontent.com/12636260/106528446-c6f98980-64b6-11eb-9317-1cb63aec2e43.png)

**Comment by Shaun-Regenbaum** [comment]
Should I go through the other values I introduced as well?

**Comment by Jutanium** [comment]
Thanks for the explanation!!

Regarding the other values, innerPadding and outerPadding make sense, but I think innerStart and outerStart should be innerStartWidth and outerStartWidth.

Regardng exception1 and exception2 (effectively booleans, so we can name them like Booleans) I like hasExtraBottomInner and hasExtraBottomOuter or something along those lines.

**Comment by Shaun-Regenbaum** [comment]
That makes sense.

**Comment by Shaun-Regenbaum** [comment]
Are you gonna update it in the main branch?

**Comment by Jutanium** [comment]
Sure, give me a bit
